require "fileutils"

module Marlon
  module Generators
    class ModuleGenerator
      def initialize(name)
        @name      = name
        @snake     = underscore(name)
        @camel     = camelize(name)
        @base_path = "lib/marlon/modules/#{@snake}"
      end

      def generate
        create_directories
        create_module_file
        create_registry
        create_default_service
        create_default_generator
        create_default_command
        create_docs_placeholder

        puts "🎉 Marlon module '#{@camel}' created at #{@base_path}"
        puts "🔥 Fully routable via Gatekeeper:"
        puts JSON.pretty_generate({
          service: "#{@camel}::Main",
          action:  "ping"
        })
      end

      private

      # ------------------------------------
      # Core directories
      # ------------------------------------
      def create_directories
        %w[services models commands generators docs].each do |dir|
          FileUtils.mkdir_p(File.join(@base_path, dir))
        end
      end

      # ------------------------------------
      # module.rb — module definition file
      # ------------------------------------
      def create_module_file
        File.write(File.join(@base_path, "module.rb"), <<~RUBY)
          module Marlon
            module Modules
              module #{@camel}
                MODULE_NAME = "#{@camel}"

                def self.root
                  File.expand_path(__dir__)
                end
              end
            end
          end
        RUBY
      end

      # ------------------------------------
      # registry.yml — declares services/actions
      # ------------------------------------
      def create_registry
        File.write(File.join(@base_path, "registry.yml"), <<~YAML)
          services:
            Main:
              actions:
                - ping
        YAML
      end

      # ------------------------------------
      # Default Service
      # ------------------------------------
      def create_default_service
        File.write(File.join(@base_path, "services/main.rb"), <<~RUBY)
          module Marlon
            module Modules
              module #{@camel}
                class Main
                  def initialize(params = {})
                    @params = params
                  end

                  def ping
                    { module: "#{@camel}", message: "pong", received: @params }
                  end
                end
              end
            end
          end
        RUBY
      end

      # ------------------------------------
      # Default Generator
      # ------------------------------------
      def create_default_generator
        File.write(File.join(@base_path, "generators/#{@snake}_generator.rb"), <<~RUBY)
          module Marlon
            module Modules
              module #{@camel}
                class #{@camel}Generator
                  def initialize(*args)
                    @args = args
                  end

                  def generate
                    puts "Generator for #{@camel} called with: \#{@args.inspect}"
                  end
                end
              end
            end
          end
        RUBY
      end

      # ------------------------------------
      # Default Command
      # ------------------------------------
      def create_default_command
        File.write(File.join(@base_path, "commands/#{@snake}_command.rb"), <<~RUBY)
          module Marlon
            module Modules
              module #{@camel}
                class #{@camel}Command
                  def self.run(*args)
                    puts "Running #{@camel}Generator..."
                    Marlon::Modules::#{@camel}::#{@camel}Generator.new(*args).generate
                  end
                end
              end
            end
          end
        RUBY
      end

      # ------------------------------------
      # Documentation placeholder
      # ------------------------------------
      def create_docs_placeholder
        File.write(File.join(@base_path, "docs/README.md"), <<~MD)
          # #{@camel} Module

          This module was generated by Marlon.

          ## Services
          - Main#ping

          ## Commands
          - marlon #{@snake}

        MD
      end

      # ------------------------------------
      # Helpers
      # ------------------------------------
      def underscore(str)
        str.gsub(/([A-Z])/, '_\1').sub(/^_/, '').downcase
      end

      def camelize(str)
        str.split('_').map(&:capitalize).join
      end
    end
  end
end
